# Getting Started with R Studio

## Load libraries

```{r}
library(tm)
library(tidyverse)
library(wordcloud2)
```


# Reading in a Text Corpus

```{r}
setwd("/Users/adra7980/Documents/diario_text/2019.11.14-ElDiarioCorpus/adverts")
```

```{r, echo=-1}
setwd("/Users/adra7980/Documents/diario_text/2019.11.14-ElDiarioCorpus/adverts")
# read in diario adverts
diario_files<-list.files(pattern=".txt")
```

```{r, echo=-1}
setwd("/Users/adra7980/Documents/diario_text/2019.11.14-ElDiarioCorpus/adverts")
# Create corpus from diario adverts
diario_adverts<-Corpus(URISource(diario_files), readerControl = list(reader=readPlain))
```


# Creating a Term Document Matrix


```{r}
# creates tdm
tdm_diario_adverts<-as.matrix(TermDocumentMatrix(diario_adverts, 
                                  control=list(removePunctuation = TRUE,
                                          stopwords = TRUE,
                                          tolower = TRUE,
                                          stemming = FALSE,
                                          removeNumbers = TRUE,
                                          bounds = list(global = c(3, Inf)))))
```

```{r, echo=F, warning=F, message=F}
library(DT)
tdm_diario_adverts_selection<-tdm_diario_adverts[1:25,1:25]
```

```{r, eval=F}
# prints "tdm_diario_adverts"
tdm_diario_adverts
```

```{r, echo=F}
tdm_diario_adverts_selection %>% datatable(extensions=c("Scroller", "FixedColumns"), options = list(
  deferRender = TRUE,
  scrollY = 350,
  scrollX = 350,
  dom = "t",
  scroller = TRUE,
  fixedColumns = list(leftColumns = 1)
))
```

# Visualizing Word Frequencies

```{r}
# word frequencies
word_frequencies<-sort(rowSums(tdm_diario_adverts), decreasing=TRUE)
```

```{r}
# Make data frame
df_word_frequencies <- data.frame(word = names(word_frequencies),freq=word_frequencies)
```


## Creating a Chart of Word Frequencies

```{r}
# ten most frequent words
df_ten<-df_word_frequencies %>% 
        slice_max(freq, n=10)
```

```{r}
diario_frequency_graph<-
  ggplot(df_ten, aes(x=reorder(word, freq), y=freq))+
    geom_bar(stat="identity")+
      coord_flip()+
      xlab("")+
      ylab("Frequency")+
      ggtitle("Ten Most Frequent Words in Diario Advertisements")+
      labs(caption = "Source: El Diario Project")
```


```{r}
diario_frequency_graph
```


## Creating a Word Cloud of Word Frequencies


```{r}
# make word cloud
wordcloud2(data = df_word_frequencies, minRotation = 0, maxRotation = 0, ellipticity = 0.2)
```


# Create bigram

```{r}
tidy_diario<-tidy(diario_adverts)
```

```{r}
tidy_diario_head<-head(tidy_diario, 25)
```

```{r, eval=F}
tidy_diario
```

```{r, echo=F}
tidy_diario_head %>% datatable(extensions=c("Scroller", "FixedColumns"), options = list(
  deferRender = TRUE,
  scrollY = 350,
  scrollX = 350,
  dom = "t",
  scroller = TRUE,
  fixedColumns = list(leftColumns = 1)
))
```


```{r}
diario_bigram<-tidy_diario %>% 
                  unnest_tokens(bigram, text, token="ngrams", n=2) %>% 
                  count(bigram, sort=TRUE)
```

```{r, echo=F}
diario_bigram_head<-head(diario_bigram, 25)
```

```{r, eval=F}
diario_bigram
```

```{r, echo=F}
diario_bigram_head %>% datatable(extensions=c("Scroller", "FixedColumns"), options = list(
  deferRender = TRUE,
  scrollY = 350,
  scrollX = 350,
  dom = "t",
  scroller = TRUE,
  fixedColumns = list(leftColumns = 1)
))
```

```{r}
diario_bigram_separated<-diario_bigram %>% 
                          separate(bigram, c("word1", "word2", sep=" "))
```


```{r}
diario_bigram_filtered<-diario_bigram_separated %>% 
                            filter(!word1 %in% stop_words$word) %>%
                            filter(!word2 %in% stop_words$word)
```

remove numbers

```{r}
diario_bigram_word1numbers<-parse_number(diario_bigram_filtered$word1)
```

```{r}
diario_bigram_word2numbers<-parse_number(diario_bigram_filtered$word2)
```


```{r}
diario_bigram_filtered<-cbind(diario_bigram_filtered, diario_bigram_word1numbers, diario_bigram_word2numbers)
```


```{r}
diario_bigram_filtered<-diario_bigram_filtered %>% 
                          filter(is.na(diario_bigram_word1numbers)) %>% 
                          filter(is.na(diario_bigram_word2numbers))
```

```{r}
diario_bigram_filtered_unite<-diario_bigram_filtered %>% 
                                unite(bigram, word1, word2, sep=" ")
```

```{r}
diario_bigram_top_ten<-diario_bigram_filtered_unite %>% 
                        slice_max(n, n=10)
```


```{r}
bigram_graph<-
  ggplot(diario_bigram_top_ten, aes(x=reorder(bigram, n), y=n))+
    geom_bar(stat="identity")+
      coord_flip()+
      xlab("")+
      ylab("Frequency")+
      ggtitle("Ten Most Frequent Co-Occuring Words in Diario Advertisements")+
      labs(caption = "Source: El Diario Project")
```


```{r}
bigram_graph
```




